/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideMenu: typeof import('./src/components/AsideMenu.vue')['default']
    Calendar: typeof import('./src/components/calendar/Calendar.vue')['default']
    CategoryDrawer: typeof import('./src/components/snippet/CategoryDrawer.vue')['default']
    CategoryInsertDialog: typeof import('./src/components/snippet/CategoryInsertDialog.vue')['default']
    Communicate: typeof import('./src/components/communicate/Communicate.vue')['default']
    EditorHeader: typeof import('./src/components/snippet/EditorHeader.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubmenu: typeof import('element-plus/es')['ElSubmenu']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./src/components/layout/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/LayoutHeader.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MarkDown: typeof import('./src/components/snippet/MarkDown.vue')['default']
    Menus: typeof import('./src/components/Menus.vue')['default']
    Other: typeof import('./src/components/other/Other.vue')['default']
    OtherQuickPlug: typeof import('./src/components/other/OtherQuickPlug.vue')['default']
    PrismEditor: typeof import('./src/components/snippet/PrismEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snippet: typeof import('./src/components/snippet/Snippet.vue')['default']
    SnippetInsertDialog: typeof import('./src/components/snippet/SnippetInsertDialog.vue')['default']
    SSH: typeof import('./src/components/other/SSH.vue')['default']
    SSHDialog: typeof import('./src/components/other/SSHDialog.vue')['default']
    Term: typeof import('./src/components/other/Term.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    Tool: typeof import('./src/components/tool/Tool.vue')['default']
    ToolHeader: typeof import('./src/components/tool/ToolHeader.vue')['default']
    ToolTable: typeof import('./src/components/tool/ToolTable.vue')['default']
    ToolUploadDialog: typeof import('./src/components/tool/ToolUploadDialog.vue')['default']
    UploadDialog: typeof import('./src/components/tool/ToolUploadDialog.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
