import {TUIComponents, TUICore, genTestUserSig} from '../TUIKit';
// import TUICallKit
import {TUICallKit} from '@tencentcloud/call-uikit-vue';


const SDKAppID = 1400814487; // Your SDKAppID
const secretKey = 'bc24d12f122541ad69329f825d7cba9e5e5cf5e3deb39939d09ceda36bfe752f'; //Your secretKey
const userID = 'administrator'; // User ID


// init TUIKit
const TUIKit = TUICore.init({
    SDKAppID,
});
// TUIKit add TUIComponents
TUIKit.use(TUIComponents);
// TUIKit add TUICallKit
TUIKit.use(TUICallKit);


// login TUIKit
TUIKit.login({
    userID: userID,
    userSig: genTestUserSig({
        SDKAppID,
        secretKey,
        userID,
    }).userSig, // The password with which the user logs in to IM. It is the ciphertext generated by encrypting information such as userID.For the detailed generation method, see Generating UserSig
});

export default TUIKit
