import request from '../utils/request'
import {LoginForm} from "@/form/user";
import {Result} from "@/result";
import {UserInfo} from "@/type/userType";
import TUIKit from "../plugin/tuikit";

export function login(data: LoginForm): Promise<Result<UserInfo>> {
    return request({
        url: '/api/v1/user/login',
        method: 'post',
        data
    })
}

export function logout(): Promise<Result> {
    return request({
        url: '/api/v1/user/logout',
        method: 'get',
    })
}


export function registry(data: FormData): Promise<Result> {
    return request({
        url: '/api/v1/user/registry',
        method: 'post',
        data
    })
}

/**
 * 登录IM
 * @param userID userID
 */
export function loginIM(userID: string, userSig: string): Promise<any> {
    // login TUIKit
    return TUIKit.login({
        userID: userID,
        userSig: userSig, // The password with which the user logs in to IM. It is the ciphertext generated by encrypting information such as userID.For the detailed generation method, see Generating UserSig
    });
}


/**
 * 登出IM
 */
export function logoutIM(): Promise<any> {
    // login TUIKit
    return TUIKit.logout();
}
