name: CI / CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: pull code
      uses: actions/checkout@v3
      with:
        # 默认当前分支
        ref: 'master'
    - name: login ali cloud
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-hangzhou.aliyuncs.com
        username: "${{ secrets.ALICLOUD_USERNAME }}"
        password: "${{ secrets.ALICLOUD_PASSWORD }}"
    - name: Build and push image
      run: |
        docker build -t registry.cn-hangzhou.aliyuncs.com/hmetao_docker/vue-code-dictionary-v3 -f Dockerfile .
        docker push registry.cn-hangzhou.aliyuncs.com/hmetao_docker/vue-code-dictionary-v3
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: /opt/jenkins_shell/front/deploy-front.sh
    
        
